title: Akash Verma blog

author:
  name: Akash Verma blog
  email: akashzsh08@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Documenting my deeplearning journey and a home for my poorly researched ideas that I find myself repeating often anyway
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://akash5100.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: akzsh5100
github_username:  akash5100

# Build settings
remote_theme: jekyll/minima

minima:
  # skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/akash5100" }
    - { platform: x,      user_url: "https://x.com/akzsh5100" }

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

disqus:
  shortname: akzsh

exclude:
  - create.py
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Makefile
